# Generated by Django 4.1.1 on 2023-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назвние')),
                ('task', models.TextField(verbose_name='Модуль')),
                ('description', models.TextField()),
            ],
        ),
    ]
